name: ci

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: leosunmo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker gen meta
        id: meta-gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/docker-gen
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gen
        uses: docker/build-push-action@v3
        with:
          file: ./gen.Dockerfile
          context: .
          build-args: |
             GEN_VERSION='${{ github.ref_name }}'
             GIT_COMMIT='${{ github.sha }}'
          push: false # No need to push here, but we would in prod.
          load: true
          tags: ${{ steps.meta-gen.outputs.tags }}
      -
        name: Run docker-gen
        run: |
          docker run --rm -v $(pwd):/workdir ${{ env.DOCKERHUB_USERNAME }}/docker-gen:${{ steps.meta-gen.outputs.version }} \
            run \
            -d /workdir/applications/hello/hello-values.yaml \
            -t /workdir/templates \
            base
      -
        name: Hello meta
        id: meta-hello
        uses: docker/metadata-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/hello
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      -
        name: Build and push hello
        uses: docker/build-push-action@v3
        with:
          file: applications/hello/Dockerfile
          context: applications/hello
          load: true
          push: false # we don't want to push here, only if it passes tests.
          tags: ${{ steps.meta-hello.outputs.tags }}
      -
        name: Test Docker image
        id: docker-run-test
        run: docker run --rm ${{ env.DOCKERHUB_USERNAME }}/hello:${{ steps.meta-hello.outputs.version }} | grep -q "Hello World"
      -
        name: Push to DockerHub
        run: |
          echo "Pushing to DockerHub"
          docker push --all-tags ${{ env.DOCKERHUB_USERNAME }}/hello